SET NOCOUNT ON;

IF OBJECT_ID('dbo.FESTIVOS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.FESTIVOS (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    fecha DATE NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    es_recurrente BIT NOT NULL CONSTRAINT DF_FESTIVOS_ES_RECURRENTE DEFAULT (0)
  );

  CREATE UNIQUE INDEX UX_FESTIVOS_FECHA
    ON dbo.FESTIVOS (fecha);
END;

IF OBJECT_ID('dbo.ATT_RULES', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ATT_RULES (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    sucursal_id INT NULL,
    horario_id INT NULL,
    tolerancia_retardo_minutos INT NOT NULL CONSTRAINT DF_ATT_RULES_TOL DEFAULT (0),
    horas_jornada_minutos INT NOT NULL CONSTRAINT DF_ATT_RULES_JORNADA DEFAULT (480),
    horas_extra_minimo_minutos INT NOT NULL CONSTRAINT DF_ATT_RULES_OT_MIN DEFAULT (0),
    horas_extra_requiere_autorizacion BIT NOT NULL CONSTRAINT DF_ATT_RULES_OT_AUT DEFAULT (0),
    aplicar_dias_festivos BIT NOT NULL CONSTRAINT DF_ATT_RULES_FESTIVOS DEFAULT (1),
    aplicar_descanso BIT NOT NULL CONSTRAINT DF_ATT_RULES_DESCANSO DEFAULT (1),
    activo BIT NOT NULL CONSTRAINT DF_ATT_RULES_ACTIVO DEFAULT (1),
    creado_en DATETIME NULL CONSTRAINT DF_ATT_RULES_CREADO DEFAULT (GETDATE()),
    actualizado_en DATETIME NULL
  );

  CREATE INDEX IX_ATT_RULES_SCOPE
    ON dbo.ATT_RULES (sucursal_id, horario_id, activo, id DESC);
END;

IF OBJECT_ID('dbo.COLABORADORES', 'U') IS NOT NULL
AND COL_LENGTH('dbo.COLABORADORES', 'pin') IS NOT NULL
BEGIN
  ALTER TABLE dbo.COLABORADORES ALTER COLUMN pin VARCHAR(255) NULL;
END;
